[config]

[config.wallpaper]
set = true

command = "swww img --transition-type center {{ image }}"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

# [templates.kitty]
# input_path = '~/.config/matugen/colors.css'
# output_path = '~/.config/kitty/themes/Matugen.conf'
# post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

# custom
[templates.ashell]
input_path = '~/.config/matugen/templates/ashell.json'
output_path = '~/.config/ashell/themes/matugen.json'
post_hook = "python ~/.config/ashell/themes/script.py"
