log_level = "ashell=debug"
outputs = "All"
position = "Bottom"

[modules]
left = [ "Clock", "SystemInfo", "WindowTitle",]
center = [ "Workspaces",]
right = [ "KeyboardLayout", "MediaPlayer", "Tray", "Settings",]

[settings]
shutdown_cmd = "poweroff"
reboot_cmd = "reboot"
logout_cmd = "hyprctl dispatch exit"
indicators = [ "Audio", "Battery", "Bluetooth", "Network",]

[appearance]
font_name = "JetBrainsMono Nerd Font Mono"
scale_factor = 1.6
success_color = "#a6e3a1"
text_color = "#cdd6f4"
style = "Solid"

[appearance.primary_color]
base = "#0d4a73"
text = "#9bcbfa"

[appearance.danger_color]
base = "#ffb4ab"
weak = "#ffb4ab"

[appearance.background_color]
base = "#101418"
weak = "#101418"
strong = "#36393e"

[appearance.secondary_color]
base = "#b9c8da"
